### ISSUE TITLE
class=project_btnが押せそうだけど押せない

### ISSUE THREAD

**Issue by nichesuch** [Code4Yokohama/code4.yokohama.obsoleted#32]
デザインを変える？
<img width="398" alt="スクリーンショット 2020-03-21 14 15 06" src="https://user-images.githubusercontent.com/2096703/77219977-60a99800-6b7e-11ea-9136-9cc9ff5a00b9.png">

プロジェクトのところにあるものはむしろ押したら動作があってもよい。
- 詳細出てくる。
- ミートアップが絞り込まれる。
など

<img width="762" alt="スクリーンショット 2020-03-21 14 13 08" src="https://user-images.githubusercontent.com/2096703/77219962-1f18ed00-6b7e-11ea-9ae2-d881b7553980.png">

**Comment by ocean3fish** [comment]
新サイトへの移行にともないこちらはクローズ
