### ISSUE TITLE
各プレスリリースのページから上部の「ハッカソン」に飛べない

### ISSUE THREAD

**Issue by rainforest0223** [Code4Yokohama/code4.yokohama.obsoleted#70]
いずれも「ハッカソン」をクリックすると「404 Not Found」になる。

**Comment by iwao** [comment]
なおしました！

**Comment by rainforest0223** [comment]
ありがとうございます。すいません説明不足でしたが、以下も同様です。

https://code4.yokohama/ICTproposal/
https://code4.yokohama/ICTproposal/report.html
https://code4.yokohama/press-release/20200503_satoyama.html
https://code4.yokohama/press-release/20200505_yokohama_to_go.html
