### ISSUE TITLE
グッズ販売サイトへのリンク張る

### ISSUE THREAD

**Issue by iwao** [Code4Yokohama/code4.yokohama.obsoleted#76]
Suzuriというサービスでcode for YOKOHAMA オリジナルTシャツやパーカーが購入できる。そちらへの動線を設定したい。売上金の使途なども明記しておいた方がいいかな。

https://suzuri.jp/C4Y

**Comment by ocean3fish** [comment]
新サイトの方で対応済みのためクローズ
