### ISSUE TITLE
よこはまYYラボとのお悩み相談会実施報告をトップページに追加

### ISSUE THREAD

**Issue by rainforest0223** [Code4Yokohama/code4.yokohama.obsoleted#87]
- 作業内容
1. https://code4.yokohama/index.html</!>　に下記コンテンツ内容を追記。

- コンテンツ内容
<h4>2020年7月30日<br></h4>
よこはまYYラボとの交流会<br>

 <p><a href="https://yylab.jimdofree.com/">横浜市職員有志で結成する自主勉強会「よこはまYYラボ」</a>とのオンライン交流会を当日夜に実施しました。参加メンバーそれぞれがアルコールも交え自己紹介を行いつつ、YYラボのみなさまが抱えているデジタルやICT分野の課題や悩みに対して、様々なバックグラウンドをもつCode for YOKOHAMAのメンバーが色々な視点や切り口で回答するといった相談会が、ゆるやかかつ賑やかに行われました。このような交流会を引き続き実施していく予定です。</p>

**Comment by nichesuch** [comment]
@rainforest0223 対応遅くなってすみません。公開したのでCloseします。
